### PR TITLE
Update english.txt

### PR DESCRIPTION
**Pull request by sandronejm**

### CODE REVIEW

**Comment by rojserbest** [comment]
@sandronejm Good, you see?

**Comment by sandronejm** [comment]
Yeaaaah 😄

**Comment by rojserbest** [comment]
@sandronejm 😁😁😁😁😁😁

I have never seen github threads with those emojis

**Comment by sandronejm** [comment]
Really? That's curious 🎉

**Comment by rojserbest** [comment]
@sandronejm hahahaha github isn't a social media

**Pull request merged**
